name: CI / CD for Angular
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

#       - name: Replace secret
#         uses: cschleiden/replace-tokens@v1
#         with:
#           tokenPrefix: '{'
#           tokenSuffix: '}'
#           files: 'src/environments/environment.prod.ts'
#         env:
#           SECRET_API_KEY: ${{ secrets.API_KEY}}

      - name: Run tests
        run: npm run test:prod

      - name: Build
        run: npm run build:prod

      - name: Upload artifact_dist
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: artifact_dist
          path: dist
  
      - name: Upload artifact_coverage
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: artifact_coverage
          path: coverage

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts created at previous job
        if: success()
        uses: actions/download-artifact@v3
        with:
          name: artifact_coverage
          path: coverage

      - name: Validate coverage
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage/pdi-01/lcov.info
          min_coverage: 80
          token: ${{ github.token }}

#      - name: Lint
#        run: npm run lint

#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v3
#         with:
#           target_branch: gh-pages
#           build_dir: dist/weather-app
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
