name: Pull Request

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate coverage report
        run: npm run test:prod
      
      - name: Upload artifact_coverage
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: artifact_coverage
          path: coverage
    
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact_coverage
        if: success()
        uses: actions/download-artifact@v3
        with:
          name: artifact_coverage
          path: coverage

      - name: Validate coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 80
          repo_token: ${{ secrets.GITHUB_TOKEN }}
